name: Laravel CI

# This action runs on every pull request that targets the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the correct PHP version
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Match your project's PHP version
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none

    # Step 3: Copy the example .env file
    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Step 4: Install Composer dependencies
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Step 5: Generate an application key
    - name: Generate an App Key
      run: php artisan key:generate

    # Step 6: Check for code style issues with Laravel Pint
    - name: Run Laravel Pint
      run: vendor/bin/pint --test

    # Step 7: Run PHPUnit tests
    - name: Run Pest/PHPUnit Tests
      run: php artisan test
